export const UserRole = {
  ATHLETE: "ATHLETE",
  PARENT: "PARENT",
  COACH: "COACH",
} as const;

export type UserRole = (typeof UserRole)[keyof typeof UserRole];

export const NoteVisibility = {
  PRIVATE: "PRIVATE",
  PROGRAM: "PROGRAM",
} as const;

export type NoteVisibility = (typeof NoteVisibility)[keyof typeof NoteVisibility];

export const BRAND = {
  primary: "#1E6BD6",
  tagline: "Direct Connection. No Middlemen.",
} as const;

export const PRICING = {
  athleteFree: { name: "Athlete — Free", price: "$0", period: "forever" },
  athletePremium: { name: "Athlete — Premium", price: "$14.99", period: "/mo or $99/yr" },
  coach: { name: "Individual Coach", price: "FREE", period: "forever" },
  program: { name: "College Program", price: "$299", period: "/mo or $2,990/yr" },
} as const;

export const SOCCER_POSITIONS = [
  "GK",
  "CB",
  "LB",
  "RB",
  "CDM",
  "CM",
  "CAM",
  "LW",
  "RW",
  "ST",
] as const;

export const GRAD_YEARS = [2025, 2026, 2027, 2028, 2029, 2030] as const;

export type ClubEntry = {
  name: string;
  league: "ECNL" | "GA" | "GA Aspire";
  conference?: string;
  city: string;
  state: string;
};

export const CLUB_ROSTER: readonly ClubEntry[] = [
  // ECNL
  { name: "Alabama FC", league: "ECNL", city: "Birmingham", state: "AL" },
  { name: "Albion Hurricanes FC", league: "ECNL", city: "Houston", state: "TX" },
  { name: "Arizona Arsenal", league: "ECNL", city: "Phoenix", state: "AZ" },
  { name: "Arlington Soccer", league: "ECNL", city: "Arlington", state: "VA" },
  { name: "Atlanta Fire United", league: "ECNL", city: "Duluth", state: "GA" },
  { name: "Beach FC (CA)", league: "ECNL", city: "Torrance", state: "CA" },
  { name: "Beach FC (VA)", league: "ECNL", city: "Virginia Beach", state: "VA" },
  { name: "Bethesda SC", league: "ECNL", city: "Gaithersburg", state: "MD" },
  { name: "Boise Timbers Thorns FC", league: "ECNL", city: "Meridian", state: "ID" },
  { name: "Carolina Elite Soccer Academy (CESA)", league: "ECNL", city: "Greenville", state: "SC" },
  { name: "Challenge SC", league: "ECNL", city: "Spring", state: "TX" },
  { name: "Charlotte Soccer Academy", league: "ECNL", city: "Pineville", state: "NC" },
  { name: "Chicago Inter", league: "ECNL", city: "New Lenox", state: "IL" },
  { name: "Classics Elite Soccer Academy", league: "ECNL", city: "San Antonio", state: "TX" },
  { name: "Cleveland Force", league: "ECNL", city: "Bedford Heights", state: "OH" },
  { name: "Colorado Rapids", league: "ECNL", city: "Aurora", state: "CO" },
  { name: "Colorado Rush", league: "ECNL", city: "Littleton", state: "CO" },
  { name: "Concorde Fire", league: "ECNL", city: "Atlanta", state: "GA" },
  { name: "Connecticut FC", league: "ECNL", city: "Bethany", state: "CT" },
  { name: "Crossfire Premier", league: "ECNL", city: "Redmond", state: "WA" },
  { name: "Dallas Texans", league: "ECNL", city: "Dallas", state: "TX" },
  { name: "Davis Legacy", league: "ECNL", city: "Davis", state: "CA" },
  { name: "De Anza Force", league: "ECNL", city: "San Jose", state: "CA" },
  { name: "D'Feeters Kicks SC (DKSC)", league: "ECNL", city: "Farmers Branch", state: "TX" },
  { name: "Eagles SC", league: "ECNL", city: "Camarillo", state: "CA" },
  { name: "East Meadow SC", league: "ECNL", city: "North Bellmore", state: "NY" },
  { name: "Eastside FC", league: "ECNL", city: "Issaquah", state: "WA" },
  { name: "Eclipse Select SC", league: "ECNL", city: "Arlington Heights", state: "IL" },
  { name: "Fairfax BRAVE", league: "ECNL", city: "Vienna", state: "VA" },
  { name: "FC Alliance", league: "ECNL", city: "Knoxville", state: "TN" },
  { name: "FC Bay Area Surf", league: "ECNL", city: "San Jose", state: "CA" },
  { name: "FC Dallas", league: "ECNL", city: "Frisco", state: "TX" },
  { name: "FC Delco", league: "ECNL", city: "Conshohocken", state: "PA" },
  { name: "FC Pride", league: "ECNL", city: "Indianapolis", state: "IN" },
  { name: "FC Prime", league: "ECNL", city: "Sunrise", state: "FL" },
  { name: "FC Stars", league: "ECNL", city: "Acton", state: "MA" },
  { name: "FC Wisconsin", league: "ECNL", city: "Germantown", state: "WI" },
  { name: "Florida Elite Soccer Academy", league: "ECNL", city: "St. Johns", state: "FL" },
  { name: "Florida Kraze Krush", league: "ECNL", city: "Winter Springs", state: "FL" },
  { name: "Florida Premier", league: "ECNL", city: "New Port Richey", state: "FL" },
  { name: "Florida West", league: "ECNL", city: "Fort Myers", state: "FL" },
  { name: "FSA FC", league: "ECNL", city: "Farmington", state: "CT" },
  { name: "Gretna Elite Academy", league: "ECNL", city: "Gretna", state: "NE" },
  { name: "Gwinnett Soccer Academy (GSA)", league: "ECNL", city: "Lilburn", state: "GA" },
  { name: "HEX FC", league: "ECNL", city: "Perkasie", state: "PA" },
  { name: "Indy Eleven", league: "ECNL", city: "Indianapolis", state: "IN" },
  { name: "Internationals SC", league: "ECNL", city: "Medina", state: "OH" },
  { name: "Jacksonville FC", league: "ECNL", city: "Jacksonville", state: "FL" },
  { name: "Kansas City Athletics", league: "ECNL", city: "Merriam", state: "KS" },
  { name: "Kings Hammer", league: "ECNL", city: "Covington", state: "KY" },
  { name: "LA Breakers FC", league: "ECNL", city: "Los Angeles", state: "CA" },
  { name: "La Roca FC", league: "ECNL", city: "South Weber", state: "UT" },
  { name: "LAFC So Cal", league: "ECNL", city: "Woodland Hills", state: "CA" },
  { name: "Legends FC", league: "ECNL", city: "Eastvale", state: "CA" },
  { name: "Legends FC San Diego", league: "ECNL", city: "San Diego", state: "CA" },
  { name: "Liverpool FC Michigan", league: "ECNL", city: "Pontiac", state: "MI" },
  { name: "LV Heat Surf", league: "ECNL", city: "Henderson", state: "NV" },
  { name: "Marin FC", league: "ECNL", city: "Greenbrae", state: "CA" },
  { name: "Maryland United FC", league: "ECNL", city: "Bowie", state: "MD" },
  { name: "Match Fit Surf (Match Fit Academy)", league: "ECNL", city: "Mercer County", state: "NJ" },
  { name: "Michigan Hawks", league: "ECNL", city: "Plymouth", state: "MI" },
  { name: "Minnesota Thunder Academy", league: "ECNL", city: "Richfield", state: "MN" },
  { name: "Mustang SC", league: "ECNL", city: "Danville", state: "CA" },
  { name: "MVLA Soccer Club", league: "ECNL", city: "Mountain View", state: "CA" },
  { name: "Nationals SC", league: "ECNL", city: "Bloomfield Hills", state: "MI" },
  { name: "NC Fusion", league: "ECNL", city: "Bermuda Run", state: "NC" },
  { name: "NCFC Youth", league: "ECNL", city: "Raleigh", state: "NC" },
  { name: "Ohio Elite Soccer Academy", league: "ECNL", city: "Cincinnati", state: "OH" },
  { name: "Ohio Premier", league: "ECNL", city: "Dublin", state: "OH" },
  { name: "Oklahoma Energy FC", league: "ECNL", city: "Edmond", state: "OK" },
  { name: "Oregon Surf", league: "ECNL", city: "Beaverton", state: "OR" },
  { name: "Orlando City Youth SC", league: "ECNL", city: "Sanford", state: "FL" },
  { name: "Pacific Northwest SC (PacNW)", league: "ECNL", city: "Tukwila", state: "WA" },
  { name: "Pateadores", league: "ECNL", city: "Costa Mesa", state: "CA" },
  { name: "Penn Fusion SA", league: "ECNL", city: "West Chester", state: "PA" },
  { name: "Philadelphia Ukrainian Nationals", league: "ECNL", city: "North Wales", state: "PA" },
  { name: "Phoenix Rising FC", league: "ECNL", city: "Scottsdale", state: "AZ" },
  { name: "Pipeline SC", league: "ECNL", city: "White Marsh", state: "MD" },
  { name: "Pittsburgh Riverhounds", league: "ECNL", city: "Pittsburgh", state: "PA" },
  { name: "Placer United", league: "ECNL", city: "Rocklin", state: "CA" },
  { name: "Players Development Academy (PDA)", league: "ECNL", city: "Somerset", state: "NJ" },
  { name: "Pleasanton Rage", league: "ECNL", city: "Pleasanton", state: "CA" },
  { name: "Portland Thorns Academy", league: "ECNL", city: "Portland", state: "OR" },
  { name: "Racing Louisville Academy", league: "ECNL", city: "Louisville", state: "KY" },
  { name: "Real Colorado", league: "ECNL", city: "Centennial", state: "CO" },
  { name: "Rebels SC", league: "ECNL", city: "Chula Vista", state: "CA" },
  { name: "Richmond United", league: "ECNL", city: "Glen Allen", state: "VA" },
  { name: "Rockford Raptors", league: "ECNL", city: "Loves Park", state: "IL" },
  { name: "St. Louis Scott Gallagher (SLSG)", league: "ECNL", city: "Fenton", state: "MO" },
  { name: "San Diego Surf SC", league: "ECNL", city: "San Diego", state: "CA" },
  { name: "San Juan SC", league: "ECNL", city: "Rancho Cordova", state: "CA" },
  { name: "Santa Rosa United", league: "ECNL", city: "Santa Rosa", state: "CA" },
  { name: "Scorpions Soccer", league: "ECNL", city: "Auburn", state: "MA" },
  { name: "Seattle United", league: "ECNL", city: "Seattle", state: "WA" },
  { name: "Slammers FC", league: "ECNL", city: "Newport Beach", state: "CA" },
  { name: "Slammers FC HB Køge", league: "ECNL", city: "Newport Beach", state: "CA" },
  { name: "So Cal Blues SC", league: "ECNL", city: "Laguna Hills", state: "CA" },
  { name: "Solar Soccer Club", league: "ECNL", city: "Allen", state: "TX" },
  { name: "South Carolina United", league: "ECNL", city: "Columbia", state: "SC" },
  { name: "South Shore Select", league: "ECNL", city: "Hingham", state: "MA" },
  { name: "Sporting Blue Valley", league: "ECNL", city: "Overland Park", state: "KS" },
  { name: "Sporting CA Arsenal FC", league: "ECNL", city: "Ontario", state: "CA" },
  { name: "Sporting Iowa", league: "ECNL", city: "Des Moines", state: "IA" },
  { name: "Sting Austin", league: "ECNL", city: "Pflugerville", state: "TX" },
  { name: "Sting Dallas", league: "ECNL", city: "Dallas", state: "TX" },
  { name: "SUSA FC", league: "ECNL", city: "Central Islip", state: "NY" },
  { name: "Tampa Bay United", league: "ECNL", city: "Tampa", state: "FL" },
  { name: "Tennessee Soccer Club", league: "ECNL", city: "Franklin", state: "TN" },
  { name: "Tulsa Soccer Club", league: "ECNL", city: "Tulsa", state: "OK" },
  { name: "United Futbol Academy", league: "ECNL", city: "Cumming", state: "GA" },
  { name: "Utah Avalanche", league: "ECNL", city: "Salt Lake City", state: "UT" },
  { name: "Utah Royals FC AZ", league: "ECNL", city: "Mesa", state: "AZ" },
  { name: "Utah Surf", league: "ECNL", city: "Pleasant Grove", state: "UT" },
  { name: "Virginia Development Academy", league: "ECNL", city: "Woodbridge", state: "VA" },
  { name: "Washington Premier", league: "ECNL", city: "Puyallup", state: "WA" },
  { name: "Wilmington Hammerheads Youth", league: "ECNL", city: "Wilmington", state: "NC" },
  { name: "WNY Flash", league: "ECNL", city: "Elma", state: "NY" },
  { name: "World Class FC", league: "ECNL", city: "Orangeburg", state: "NY" },
  // GA — Frontier
  { name: "Atletico Dallas Youth", league: "GA", conference: "Frontier", city: "Richardson", state: "TX" },
  { name: "BVB International Academy", league: "GA", conference: "Frontier", city: "Carrollton", state: "TX" },
  { name: "Dallas Surf", league: "GA", conference: "Frontier", city: "Dallas", state: "TX" },
  { name: "HTX Soccer", league: "GA", conference: "Frontier", city: "Houston", state: "TX" },
  { name: "Lou Fusz Athletic", league: "GA", conference: "Frontier", city: "St. Louis", state: "MO" },
  { name: "Louisiana Elite", league: "GA", conference: "Frontier", city: "Baton Rouge", state: "LA" },
  { name: "RISE SC", league: "GA", conference: "Frontier", city: "Houston", state: "TX" },
  { name: "San Antonio City SC", league: "GA", conference: "Frontier", city: "San Antonio", state: "TX" },
  { name: "St. Louis Development Academy", league: "GA", conference: "Frontier", city: "St. Louis", state: "MO" },
  { name: "Tulsa SC", league: "GA", conference: "Frontier", city: "Tulsa", state: "OK" },
  // GA — Mid-America
  { name: "Beadling SC", league: "GA", conference: "Mid-America", city: "Bridgeville", state: "PA" },
  { name: "Century United", league: "GA", conference: "Mid-America", city: "Pittsburgh", state: "PA" },
  { name: "Club Ohio", league: "GA", conference: "Mid-America", city: "Columbus", state: "OH" },
  { name: "Columbus United", league: "GA", conference: "Mid-America", city: "Columbus", state: "OH" },
  { name: "Cincinnati United Premier Gold", league: "GA", conference: "Mid-America", city: "Cincinnati", state: "OH" },
  { name: "Indy Premier United", league: "GA", conference: "Mid-America", city: "Noblesville", state: "IN" },
  { name: "Kings Hammer SC", league: "GA", conference: "Mid-America", city: "Cincinnati", state: "OH" },
  { name: "Nashville United", league: "GA", conference: "Mid-America", city: "Nashville", state: "TN" },
  { name: "One Knoxville SC", league: "GA", conference: "Mid-America", city: "Knoxville", state: "TN" },
  // GA — Midwest East
  { name: "Central Illinois United", league: "GA", conference: "Midwest — East", city: "Rantoul", state: "IL" },
  { name: "Chicago FC United", league: "GA", conference: "Midwest — East", city: "Chicago", state: "IL" },
  { name: "Elmbrook United", league: "GA", conference: "Midwest — East", city: "Brookfield", state: "WI" },
  { name: "Galaxy SC", league: "GA", conference: "Midwest — East", city: "Naperville", state: "IL" },
  { name: "Madison 56ers", league: "GA", conference: "Midwest — East", city: "Madison", state: "WI" },
  { name: "Michigan Jaguars FC", league: "GA", conference: "Midwest — East", city: "Novi", state: "MI" },
  { name: "Michigan Tigers", league: "GA", conference: "Midwest — East", city: "Ann Arbor", state: "MI" },
  { name: "Midwest United", league: "GA", conference: "Midwest — East", city: "Kentwood", state: "MI" },
  { name: "Sockers FC", league: "GA", conference: "Midwest — East", city: "Chicago", state: "IL" },
  // GA — Midwest West
  { name: "Kansas Rush SC", league: "GA", conference: "Midwest — West", city: "Olathe", state: "KS" },
  { name: "North Shore United", league: "GA", conference: "Midwest — West", city: "Milwaukee", state: "WI" },
  { name: "Salvo SC", league: "GA", conference: "Midwest — West", city: "Rosemount", state: "MN" },
  { name: "SC Wave", league: "GA", conference: "Midwest — West", city: "Brookfield", state: "WI" },
  { name: "Sporting City", league: "GA", conference: "Midwest — West", city: "Kansas City", state: "MO" },
  { name: "Sporting Nebraska FC", league: "GA", conference: "Midwest — West", city: "Omaha", state: "NE" },
  { name: "Tonka Fusion Elite", league: "GA", conference: "Midwest — West", city: "Plymouth", state: "MN" },
  { name: "Union KC SC", league: "GA", conference: "Midwest — West", city: "Kansas City", state: "MO" },
  { name: "VSA Rush", league: "GA", conference: "Midwest — West", city: "Waukee", state: "IA" },
  // GA — Mid-Atlantic North
  { name: "Baltimore Armour", league: "GA", conference: "Mid-Atlantic — North", city: "Baltimore", state: "MD" },
  { name: "Baltimore Celtic", league: "GA", conference: "Mid-Atlantic — North", city: "Baltimore", state: "MD" },
  { name: "Coppermine SC", league: "GA", conference: "Mid-Atlantic — North", city: "Baltimore", state: "MD" },
  { name: "Keystone FC", league: "GA", conference: "Mid-Atlantic — North", city: "Mechanicsburg", state: "PA" },
  { name: "LVU Rush", league: "GA", conference: "Mid-Atlantic — North", city: "Lehigh Valley", state: "PA" },
  { name: "PA Classics", league: "GA", conference: "Mid-Atlantic — North", city: "Manheim", state: "PA" },
  { name: "Real Futbol Academy", league: "GA", conference: "Mid-Atlantic — North", city: "Medford", state: "NJ" },
  { name: "SJEB FC", league: "GA", conference: "Mid-Atlantic — North", city: "Pitman", state: "NJ" },
  { name: "Sporting Athletic Club", league: "GA", conference: "Mid-Atlantic — North", city: "Wilmington", state: "DE" },
  // GA — Mid-Atlantic South
  { name: "Alexandria SA", league: "GA", conference: "Mid-Atlantic — South", city: "Alexandria", state: "VA" },
  { name: "Charlotte DA", league: "GA", conference: "Mid-Atlantic — South", city: "Charlotte", state: "NC" },
  { name: "Charlotte Independence SC", league: "GA", conference: "Mid-Atlantic — South", city: "Cornelius", state: "NC" },
  { name: "Loudoun SC", league: "GA", conference: "Mid-Atlantic — South", city: "Leesburg", state: "VA" },
  { name: "McLean YS", league: "GA", conference: "Mid-Atlantic — South", city: "McLean", state: "VA" },
  { name: "Northern Virginia Alliance", league: "GA", conference: "Mid-Atlantic — South", city: "Leesburg", state: "VA" },
  { name: "Skyline Elite SC", league: "GA", conference: "Mid-Atlantic — South", city: "Charlottesville", state: "VA" },
  { name: "Springfield Youth Club", league: "GA", conference: "Mid-Atlantic — South", city: "Springfield", state: "VA" },
  { name: "The St. James FC", league: "GA", conference: "Mid-Atlantic — South", city: "Leesburg", state: "VA" },
  { name: "Triangle United", league: "GA", conference: "Mid-Atlantic — South", city: "Chapel Hill", state: "NC" },
  { name: "VA Revolution", league: "GA", conference: "Mid-Atlantic — South", city: "Leesburg", state: "VA" },
  { name: "Wake FC", league: "GA", conference: "Mid-Atlantic — South", city: "Holly Springs", state: "NC" },
  // GA — Mountain West
  { name: "Albion SC Las Vegas", league: "GA", conference: "Mountain West", city: "Las Vegas", state: "NV" },
  { name: "Broomfield SC", league: "GA", conference: "Mountain West", city: "Broomfield", state: "CO" },
  { name: "Colorado United", league: "GA", conference: "Mountain West", city: "Littleton", state: "CO" },
  { name: "Las Vegas Sports Academy", league: "GA", conference: "Mountain West", city: "Las Vegas", state: "NV" },
  { name: "New Mexico Soccer Academy", league: "GA", conference: "Mountain West", city: "Albuquerque", state: "NM" },
  { name: "NM Rapids", league: "GA", conference: "Mountain West", city: "Albuquerque", state: "NM" },
  { name: "Utah Celtic FC", league: "GA", conference: "Mountain West", city: "Highland", state: "UT" },
  { name: "Wasatch SC", league: "GA", conference: "Mountain West", city: "Kaysville", state: "UT" },
  // GA — Northeast
  { name: "Bayside FC", league: "GA", conference: "Northeast", city: "Providence", state: "RI" },
  { name: "Cedar Stars Academy – Bergen", league: "GA", conference: "Northeast", city: "Teaneck", state: "NJ" },
  { name: "Cedar Stars Academy – Monmouth", league: "GA", conference: "Northeast", city: "Tinton Falls", state: "NJ" },
  { name: "Downtown United SC", league: "GA", conference: "Northeast", city: "New York", state: "NY" },
  { name: "Long Island SC", league: "GA", conference: "Northeast", city: "Garden City", state: "NY" },
  { name: "NEFC Navy", league: "GA", conference: "Northeast", city: "Mendon", state: "MA" },
  { name: "NEFC Red", league: "GA", conference: "Northeast", city: "Mendon", state: "MA" },
  { name: "New York SC", league: "GA", conference: "Northeast", city: "Purchase", state: "NY" },
  { name: "Oakwood SC", league: "GA", conference: "Northeast", city: "Glastonbury", state: "CT" },
  { name: "Rhode Island Surf", league: "GA", conference: "Northeast", city: "North Kingstown", state: "RI" },
  { name: "Rochester NYFC Youth", league: "GA", conference: "Northeast", city: "West Henrietta", state: "NY" },
  { name: "SDA", league: "GA", conference: "Northeast", city: "Solvay", state: "NY" },
  { name: "Seacoast United", league: "GA", conference: "Northeast", city: "Epping", state: "NH" },
  { name: "STA", league: "GA", conference: "Northeast", city: "Morris Plains", state: "NJ" },
  // GA — Northwest
  { name: "1974 Newark FC", league: "GA", conference: "Northwest", city: "Newark", state: "CA" },
  { name: "Ajax United", league: "GA", conference: "Northwest", city: "Modesto", state: "CA" },
  { name: "Almaden FC", league: "GA", conference: "Northwest", city: "San Jose", state: "CA" },
  { name: "Blues FC", league: "GA", conference: "Northwest", city: "Rocklin", state: "CA" },
  { name: "Clovis Crossfire", league: "GA", conference: "Northwest", city: "Clovis", state: "CA" },
  { name: "Lamorinda SC", league: "GA", conference: "Northwest", city: "Orinda", state: "CA" },
  { name: "Napa United", league: "GA", conference: "Northwest", city: "Napa", state: "CA" },
  { name: "Sacramento United", league: "GA", conference: "Northwest", city: "Sacramento", state: "CA" },
  { name: "Santa Clara Sporting", league: "GA", conference: "Northwest", city: "Santa Clara", state: "CA" },
  { name: "SF Glens", league: "GA", conference: "Northwest", city: "San Francisco", state: "CA" },
  { name: "Silicon Valley SA", league: "GA", conference: "Northwest", city: "Palo Alto", state: "CA" },
  { name: "South Valley Surf", league: "GA", conference: "Northwest", city: "Bakersfield", state: "CA" },
  // GA — Pacific Northwest
  { name: "Capital FC", league: "GA", conference: "Pacific Northwest", city: "Salem", state: "OR" },
  { name: "Columbia Premier SC", league: "GA", conference: "Pacific Northwest", city: "Vancouver", state: "WA" },
  { name: "Eugene Metro FC", league: "GA", conference: "Pacific Northwest", city: "Eugene", state: "OR" },
  { name: "Oregon Premier", league: "GA", conference: "Pacific Northwest", city: "West Linn", state: "OR" },
  { name: "Seattle Celtic", league: "GA", conference: "Pacific Northwest", city: "Seattle", state: "WA" },
  { name: "Seattle Reign Academy", league: "GA", conference: "Pacific Northwest", city: "Tacoma", state: "WA" },
  { name: "Spokane Shadow", league: "GA", conference: "Pacific Northwest", city: "Spokane", state: "WA" },
  { name: "United PDX", league: "GA", conference: "Pacific Northwest", city: "Portland", state: "OR" },
  { name: "Washington East Surf SC", league: "GA", conference: "Pacific Northwest", city: "Spokane", state: "WA" },
  { name: "Washington Rush", league: "GA", conference: "Pacific Northwest", city: "Everett", state: "WA" },
  { name: "Western Washington Surf", league: "GA", conference: "Pacific Northwest", city: "Bellevue", state: "WA" },
  { name: "Westside Metros", league: "GA", conference: "Pacific Northwest", city: "Beaverton", state: "OR" },
  // GA — Southeast
  { name: "Florida United", league: "GA", conference: "Southeast", city: "Miramar", state: "FL" },
  { name: "Hoover-Vestavia Soccer", league: "GA", conference: "Southeast", city: "Birmingham", state: "AL" },
  { name: "IMG Academy", league: "GA", conference: "Southeast", city: "Bradenton", state: "FL" },
  { name: "Palm Beach United", league: "GA", conference: "Southeast", city: "Palm Beach Gardens", state: "FL" },
  { name: "Pinecrest Premier", league: "GA", conference: "Southeast", city: "Miami", state: "FL" },
  { name: "Southern Soccer Academy", league: "GA", conference: "Southeast", city: "Marietta", state: "GA" },
  { name: "Space Coast United SC", league: "GA", conference: "Southeast", city: "Melbourne", state: "FL" },
  { name: "Tophat Gold", league: "GA", conference: "Southeast", city: "Marietta", state: "GA" },
  { name: "Tophat Navy", league: "GA", conference: "Southeast", city: "Marietta", state: "GA" },
  { name: "West Florida Flames", league: "GA", conference: "Southeast", city: "Apollo Beach", state: "FL" },
  // GA — Southwest
  { name: "Albion SC San Diego", league: "GA", conference: "Southwest", city: "San Diego", state: "CA" },
  { name: "City SC Blue", league: "GA", conference: "Southwest", city: "Carlsbad", state: "CA" },
  { name: "City SC White", league: "GA", conference: "Southwest", city: "Carlsbad", state: "CA" },
  { name: "FC Tucson", league: "GA", conference: "Southwest", city: "Tucson", state: "AZ" },
  { name: "FRAM SC", league: "GA", conference: "Southwest", city: "Torrance", state: "CA" },
  { name: "LA Surf SC", league: "GA", conference: "Southwest", city: "Pasadena", state: "CA" },
  { name: "SoCal Reds FC", league: "GA", conference: "Southwest", city: "Irvine", state: "CA" },
  { name: "City SC Southwest", league: "GA", conference: "Southwest", city: "Temecula", state: "CA" },
  { name: "Rangers FC", league: "GA", conference: "Southwest", city: "Fullerton", state: "CA" },
  { name: "SC del Sol", league: "GA", conference: "Southwest", city: "Phoenix", state: "AZ" },
  { name: "SDSC Surf", league: "GA", conference: "Southwest", city: "San Diego", state: "CA" },
  { name: "West Coast FC", league: "GA", conference: "Southwest", city: "Irvine", state: "CA" },
  // GA Aspire — Southwest
  { name: "ALBION SC San Diego", league: "GA Aspire", conference: "Southwest", city: "San Diego", state: "CA" },
  { name: "City SC", league: "GA Aspire", conference: "Southwest", city: "Carlsbad", state: "CA" },
  { name: "FRAM SC", league: "GA Aspire", conference: "Southwest", city: "Torrance", state: "CA" },
  { name: "LA Surf SC", league: "GA Aspire", conference: "Southwest", city: "Pasadena", state: "CA" },
  { name: "SDSC Surf", league: "GA Aspire", conference: "Southwest", city: "San Diego", state: "CA" },
  { name: "SoCal Reds FC", league: "GA Aspire", conference: "Southwest", city: "Irvine", state: "CA" },
  { name: "California Football Academy", league: "GA Aspire", conference: "Southwest", city: "Laguna Hills", state: "CA" },
  { name: "Santa Barbara SC", league: "GA Aspire", conference: "Southwest", city: "Santa Barbara", state: "CA" },
  { name: "Sand and Surf SC", league: "GA Aspire", conference: "Southwest", city: "Manhattan Beach", state: "CA" },
  // GA Aspire — Pacific Northwest
  { name: "Sting SC", league: "GA Aspire", conference: "Pacific Northwest", city: "Coeur d'Alene", state: "ID" },
  { name: "Soccer Chance Academy", league: "GA Aspire", conference: "Pacific Northwest", city: "Portland", state: "OR" },
  { name: "Bend FC", league: "GA Aspire", conference: "Pacific Northwest", city: "Bend", state: "OR" },
  { name: "Eugene Metro FC", league: "GA Aspire", conference: "Pacific Northwest", city: "Eugene", state: "OR" },
  { name: "Portland City United SC", league: "GA Aspire", conference: "Pacific Northwest", city: "Portland", state: "OR" },
  { name: "Mt. Rainier FC", league: "GA Aspire", conference: "Pacific Northwest", city: "Buckley", state: "WA" },
  { name: "Seattle Reign Academy", league: "GA Aspire", conference: "Pacific Northwest", city: "Seattle", state: "WA" },
  { name: "Spokane Shadow", league: "GA Aspire", conference: "Pacific Northwest", city: "Spokane", state: "WA" },
  { name: "Washington East Surf – Columbia Basin", league: "GA Aspire", conference: "Pacific Northwest", city: "Pasco", state: "WA" },
  { name: "Washington East Surf SC", league: "GA Aspire", conference: "Pacific Northwest", city: "Spokane", state: "WA" },
  { name: "Western Washington Surf", league: "GA Aspire", conference: "Pacific Northwest", city: "Bellevue", state: "WA" },
  { name: "Valor Soccer", league: "GA Aspire", conference: "Pacific Northwest", city: "Maple Valley", state: "WA" },
  { name: "Columbia Premier SC", league: "GA Aspire", conference: "Pacific Northwest", city: "Vancouver", state: "WA" },
  // GA Aspire — Mountain West
  { name: "Arizona SC", league: "GA Aspire", conference: "Mountain West", city: "Gilbert", state: "AZ" },
  { name: "SC del Sol", league: "GA Aspire", conference: "Mountain West", city: "Phoenix", state: "AZ" },
  { name: "Phoenix Premier FC", league: "GA Aspire", conference: "Mountain West", city: "Phoenix", state: "AZ" },
  { name: "CCV Stars SC", league: "GA Aspire", conference: "Mountain West", city: "Peoria", state: "AZ" },
  { name: "ALBION SC Las Vegas", league: "GA Aspire", conference: "Mountain West", city: "Las Vegas", state: "NV" },
  { name: "Black Diamond FC", league: "GA Aspire", conference: "Mountain West", city: "Bountiful", state: "UT" },
  { name: "Utah Celtic", league: "GA Aspire", conference: "Mountain West", city: "Orem", state: "UT" },
  { name: "Impact United", league: "GA Aspire", conference: "Mountain West", city: "Salt Lake City", state: "UT" },
  { name: "Wasatch SC", league: "GA Aspire", conference: "Mountain West", city: "Kaysville", state: "UT" },
  // GA Aspire — Lonestar
  { name: "GFI Academy", league: "GA Aspire", conference: "Lonestar", city: "Houston", state: "TX" },
  { name: "Dallas Surf SC", league: "GA Aspire", conference: "Lonestar", city: "Dallas", state: "TX" },
  { name: "HTX – North", league: "GA Aspire", conference: "Lonestar", city: "Houston", state: "TX" },
  { name: "HTX – South", league: "GA Aspire", conference: "Lonestar", city: "Houston", state: "TX" },
  { name: "San Antonio City SC", league: "GA Aspire", conference: "Lonestar", city: "San Antonio", state: "TX" },
  { name: "Capital City SC", league: "GA Aspire", conference: "Lonestar", city: "Austin", state: "TX" },
  { name: "Houston Surf", league: "GA Aspire", conference: "Lonestar", city: "Houston", state: "TX" },
  // GA Aspire — Great Lakes
  { name: "Galaxy SC", league: "GA Aspire", conference: "Great Lakes", city: "Naperville", state: "IL" },
  { name: "Chicago FC United", league: "GA Aspire", conference: "Great Lakes", city: "Glenview", state: "IL" },
  { name: "Sockers FC", league: "GA Aspire", conference: "Great Lakes", city: "Palatine", state: "IL" },
  { name: "Wheaton United SC", league: "GA Aspire", conference: "Great Lakes", city: "Wheaton", state: "IL" },
  { name: "Michigan Jaguars", league: "GA Aspire", conference: "Great Lakes", city: "Novi", state: "MI" },
  { name: "Midwest United", league: "GA Aspire", conference: "Great Lakes", city: "Kentwood", state: "MI" },
  { name: "Midwest United FC SCOR", league: "GA Aspire", conference: "Great Lakes", city: "Rockford", state: "MI" },
  { name: "Michigan Stars Elite SC", league: "GA Aspire", conference: "Great Lakes", city: "Washington", state: "MI" },
  { name: "Elmbrook United", league: "GA Aspire", conference: "Great Lakes", city: "Brookfield", state: "WI" },
  { name: "Wisconsin United SC", league: "GA Aspire", conference: "Great Lakes", city: "Appleton", state: "WI" },
  { name: "North Shore United", league: "GA Aspire", conference: "Great Lakes", city: "Cedarburg", state: "WI" },
  { name: "SC Wave", league: "GA Aspire", conference: "Great Lakes", city: "Brookfield", state: "WI" },
  // GA Aspire — Mid-America
  { name: "Indy Premier SC", league: "GA Aspire", conference: "Mid-America", city: "Noblesville", state: "IN" },
  { name: "Javanon FC", league: "GA Aspire", conference: "Mid-America", city: "Louisville", state: "KY" },
  { name: "Kings Hammer SC NKY", league: "GA Aspire", conference: "Mid-America", city: "Cincinnati", state: "OH" },
  { name: "Cincinnati United BLACK", league: "GA Aspire", conference: "Mid-America", city: "Cincinnati", state: "OH" },
  { name: "Club Ohio", league: "GA Aspire", conference: "Mid-America", city: "Dublin", state: "OH" },
  { name: "Kings Hammer SC TN", league: "GA Aspire", conference: "Mid-America", city: "Nashville", state: "TN" },
  // GA Aspire — Mid-Atlantic South
  { name: "Carolina Core", league: "GA Aspire", conference: "Mid-Atlantic — South", city: "High Point", state: "NC" },
  { name: "Wake FC", league: "GA Aspire", conference: "Mid-Atlantic — South", city: "Holly Springs", state: "NC" },
  { name: "McLean YS", league: "GA Aspire", conference: "Mid-Atlantic — South", city: "McLean", state: "VA" },
  { name: "VA Rush SC", league: "GA Aspire", conference: "Mid-Atlantic — South", city: "Virginia Beach", state: "VA" },
  { name: "Virginia Revolution SC", league: "GA Aspire", conference: "Mid-Atlantic — South", city: "Leesburg", state: "VA" },
  { name: "Springfield SYC Soccer", league: "GA Aspire", conference: "Mid-Atlantic — South", city: "Springfield", state: "VA" },
  { name: "Loudoun SC", league: "GA Aspire", conference: "Mid-Atlantic — South", city: "Leesburg", state: "VA" },
  { name: "FC Richmond", league: "GA Aspire", conference: "Mid-Atlantic — South", city: "Richmond", state: "VA" },
  { name: "Alexandria SA", league: "GA Aspire", conference: "Mid-Atlantic — South", city: "Alexandria", state: "VA" },
  // GA Aspire — Mid-Atlantic North
  { name: "The Player Progression Academy", league: "GA Aspire", conference: "Mid-Atlantic — North", city: "Washington", state: "DC" },
  { name: "Potomac SA", league: "GA Aspire", conference: "Mid-Atlantic — North", city: "Germantown", state: "MD" },
  { name: "Coppermine SC", league: "GA Aspire", conference: "Mid-Atlantic — North", city: "Baltimore", state: "MD" },
  { name: "Baltimore Armour", league: "GA Aspire", conference: "Mid-Atlantic — North", city: "Ellicott City", state: "MD" },
  { name: "Baltimore Celtic SC", league: "GA Aspire", conference: "Mid-Atlantic — North", city: "Baltimore", state: "MD" },
  { name: "Keystone FC", league: "GA Aspire", conference: "Mid-Atlantic — North", city: "Mechanicsburg", state: "PA" },
  { name: "Huntingdon Valley AA", league: "GA Aspire", conference: "Mid-Atlantic — North", city: "Huntingdon Valley", state: "PA" },
  { name: "LVU Rush", league: "GA Aspire", conference: "Mid-Atlantic — North", city: "Lehigh Valley", state: "PA" },
  // GA Aspire — New England
  { name: "Ginga FC", league: "GA Aspire", conference: "New England", city: "Woodbridge", state: "CT" },
  { name: "NEFC", league: "GA Aspire", conference: "New England", city: "Mendon", state: "MA" },
  { name: "Seacoast United Massachusetts", league: "GA Aspire", conference: "New England", city: "Weymouth", state: "MA" },
  { name: "IFA", league: "GA Aspire", conference: "New England", city: "Boston", state: "MA" },
  { name: "FC Boston Bolts", league: "GA Aspire", conference: "New England", city: "Boston", state: "MA" },
  { name: "Seacoast United NH", league: "GA Aspire", conference: "New England", city: "Hampton", state: "NH" },
  // GA Aspire — Northeast
  { name: "STA", league: "GA Aspire", conference: "Northeast", city: "Randolph", state: "NJ" },
  { name: "NJ Premier", league: "GA Aspire", conference: "Northeast", city: "Somerset", state: "NJ" },
  { name: "The Football Academy", league: "GA Aspire", conference: "Northeast", city: "Florham Park", state: "NJ" },
  { name: "New York SC", league: "GA Aspire", conference: "Northeast", city: "Westchester", state: "NY" },
  { name: "Long Island SC", league: "GA Aspire", conference: "Northeast", city: "Long Island", state: "NY" },
  { name: "Atlantic United", league: "GA Aspire", conference: "Northeast", city: "Stony Brook", state: "NY" },
  { name: "New York City FC", league: "GA Aspire", conference: "Northeast", city: "New York City", state: "NY" },
  // GA Aspire — Southeast
  { name: "Tophat", league: "GA Aspire", conference: "Southeast", city: "Atlanta", state: "GA" },
  { name: "AFC Lightning", league: "GA Aspire", conference: "Southeast", city: "Peachtree City", state: "GA" },
  { name: "Georgia Impact SC", league: "GA Aspire", conference: "Southeast", city: "Canton", state: "GA" },
  { name: "Inter Atlanta FC", league: "GA Aspire", conference: "Southeast", city: "Atlanta", state: "GA" },
  { name: "Charlotte Independence SC North", league: "GA Aspire", conference: "Southeast", city: "Charlotte", state: "NC" },
  { name: "Fox Soccer Academy of the Carolinas", league: "GA Aspire", conference: "Southeast", city: "Charlotte", state: "NC" },
  { name: "Charlotte Independence SC South", league: "GA Aspire", conference: "Southeast", city: "Charlotte", state: "NC" },
  { name: "Lowcountry United SC", league: "GA Aspire", conference: "Southeast", city: "Charleston", state: "SC" },
  // GA Aspire — Midwest
  { name: "Kansas Rush", league: "GA Aspire", conference: "Midwest", city: "Olathe", state: "KS" },
  { name: "KC Fusion", league: "GA Aspire", conference: "Midwest", city: "Kansas City", state: "KS" },
  { name: "Kansas City Legends", league: "GA Aspire", conference: "Midwest", city: "Kansas City", state: "KS" },
  { name: "Toca FC", league: "GA Aspire", conference: "Midwest", city: "Olathe", state: "KS" },
  { name: "St. Louis Development Academy", league: "GA Aspire", conference: "Midwest", city: "St. Louis", state: "MO" },
  { name: "Lou Fusz Athletic Gold", league: "GA Aspire", conference: "Midwest", city: "St. Louis", state: "MO" },
  { name: "Union KC SC", league: "GA Aspire", conference: "Midwest", city: "Kansas City", state: "MO" },
  { name: "Lou Fusz Athletic White", league: "GA Aspire", conference: "Midwest", city: "St. Louis", state: "MO" },
] as const;

export const DIVISIONS = ["D1", "D2", "D3", "NAIA", "JUCO"] as const;

export const US_REGIONS = [
  "Northeast",
  "Southeast",
  "Midwest",
  "Southwest",
  "West",
] as const;
